openapi: 3.0.0
info:
  title: RAG Agent API
  description: API for processing user queries through the RAG agent
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /agent/query:
    post:
      summary: Process a user query through the RAG agent
      description: Submit a query to the RAG agent for processing with retrieval-augmented generation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response from the RAG agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /agent/health:
    get:
      summary: Check the health status of the agent service
      description: Verify that the agent service is running and accessible
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        '500':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's question or query
          example: "What is ROS2 and how does it differ from ROS1?"
          minLength: 1
          maxLength: 2000
        stream:
          type: boolean
          description: Whether to stream responses (optional)
          default: false

    AgentResponse:
      type: object
      required:
        - answer
        - sources
        - matched_chunks
        - query_time_ms
        - confidence
      properties:
        answer:
          type: string
          description: The agent's response to the query
          example: "ROS2 is the next generation of Robot Operating System..."
        sources:
          type: array
          items:
            type: string
          description: URLs of documents used as sources
          example: ["https://docs.ros.org/en/rolling/"]
        matched_chunks:
          type: array
          items:
            $ref: '#/components/schemas/MatchedChunk'
          description: Chunks of content that were matched during retrieval
        query_time_ms:
          type: number
          description: Time taken to process the query in milliseconds
          example: 1250
        confidence:
          type: string
          description: Confidence level of the response
          enum: [high, medium, low]
          example: "high"

    MatchedChunk:
      type: object
      required:
        - content
        - source_url
        - similarity_score
      properties:
        content:
          type: string
          description: Content of the matched chunk
          example: "ROS2 is designed to be a flexible framework for writing robot software..."
        source_url:
          type: string
          description: URL of the source document
          example: "https://docs.ros.org/en/rolling/Concepts.html"
        similarity_score:
          type: number
          description: Similarity score of the match
          example: 0.85
          format: float

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: Error code
              example: "INTERNAL_ERROR"
            message:
              type: string
              description: Error message
              example: "An internal error occurred during query processing"